// <auto-generated />
using System;
using System.Collections.Generic;
using AISandbox.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AISandbox.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261005093050_AddQuestionSets")]
    partial class AddQuestionSets
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("AISandbox.Domain.Authoring.QuestionSets.QuestionSet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Questions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("QuestionSets", (string)null);
                });

            modelBuilder.Entity("AISandbox.Domain.Catalog.Models.ModelDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Capabilities")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSchema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Origin")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSchema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Pricing")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.ToTable("ModelDefinitions", (string)null);
                });

            modelBuilder.Entity("AISandbox.Domain.Catalog.Providers.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Secret", "AISandbox.Domain.Catalog.Providers.Provider.Secret#SecretReference", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("EnvironmentVariable")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("SecretEnvironmentVariable");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("SecretName");
                        });

                    b.HasKey("Id");

                    b.ToTable("Providers", (string)null);
                });

            modelBuilder.Entity("AISandbox.Domain.Experimentation.Run", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("Runs", (string)null);
                });

            modelBuilder.Entity("AISandbox.Infrastructure.Secrets.StoredSecret", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("Secrets", (string)null);
                });

            modelBuilder.Entity("AISandbox.Domain.Catalog.Models.ModelDefinition", b =>
                {
                    b.HasOne("AISandbox.Domain.Catalog.Providers.Provider", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AISandbox.Domain.Experimentation.Run", b =>
                {
                    b.OwnsMany("AISandbox.Domain.Experimentation.ModelExecution", "Executions", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Attempts")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTimeOffset?>("CompletedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Cost")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CostSource")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Error")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Latency")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Output")
                                .HasColumnType("TEXT");

                            b1.Property<string>("RawRequest")
                                .HasColumnType("TEXT");

                            b1.Property<string>("RawResponse")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ResolvedModel")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("RunId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset?>("StartedAt")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Usage")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("RunId");

                            b1.ToTable("Executions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RunId");
                        });

                    b.Navigation("Executions");
                });
#pragma warning restore 612, 618
        }
    }
}
